name: rlusd

services:
  database:
    image: postgres:17
    ports:
      - "5469:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: rlusd
      POSTGRES_PASSWORD: rlusd1234!
      POSTGRES_DB: rlusd

volumes:
  postgres-data:
